name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'image/**'
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'image/**'


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        cd trace
        go mod download

    - name: Run tests
      run: |
        cd trace
        go test -v ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: trace
        args: --timeout=5m
